### ISSUE TITLE
ImportError: cannot import name 'PunktTokenizer' from 'nltk.tokenize'

### ISSUE THREAD

**Issue by lalo** [microsoft/eureka-ml-insights#32]
Possible solution:

https://github.com/microsoft/eureka-ml-insights/blob/34c2fbc3686120ae85762612cfa08affd5c0154b/eureka_ml_insights/metrics/ifeval_instruction_utils.py#L1673

move to ```from nltk.tokenize.punkt import PunktTokenizer```

Error trace:

```
Inference Progress:: 100%|██████████| 541/541 [2:04:41<00:00,  6.27s/it]
Inference Progress:: 100%|██████████| 541/541 [2:04:41<00:00, 13.83s/it]
data.py - _load_dataset - Loading JSONL Data From logs/IFEval_PIPELINE/o1-preview/2024-10-10-21-15-40.329361/inference_result/inference_result.jsonl.
data.py - load_dataset - Loaded dataset with shape: (541, 9)
data.py - load_dataset - Transformed dataset has shape: (541, 9)
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
Traceback (most recent call last):
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/ms_main.py", line 43, in <module>
    pipeline.run()
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/core/pipeline.py", line 39, in run
    component.run()
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/core/eval_reporting.py", line 39, in run
    metric_result = self.metric.evaluate(df)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/metrics_base.py", line 26, in evaluate
    super().evaluate(data)
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/metrics_base.py", line 16, in evaluate
    data[self.__class__.__name__ + "_result"] = data.apply(lambda x: self.__evaluate__(x), axis=1)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/azureml_5fab4ad31daaaef6f9e1df39f28761b7/lib/python3.11/site-packages/pandas/core/frame.py", line 10361, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/azureml-envs/azureml_5fab4ad31daaaef6f9e1df39f28761b7/lib/python3.11/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/azureml_5fab4ad31daaaef6f9e1df39f28761b7/lib/python3.11/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/azureml_5fab4ad31daaaef6f9e1df39f28761b7/lib/python3.11/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/metrics_base.py", line 16, in <lambda>
    data[self.__class__.__name__ + "_result"] = data.apply(lambda x: self.__evaluate__(x), axis=1)
                                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_metrics.py", line 37, in __evaluate__
    return self.evaluate_instruction_following(row)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_metrics.py", line 41, in evaluate_instruction_following
    results_strict = test_instruction_following_strict(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_instruction_utils.py", line 3340, in test_instruction_following_strict
    if response.strip() and instruction.check_following(response):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_instruction_utils.py", line 1892, in check_following
    num_sentences = count_sentences(value)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_instruction_utils.py", line 1679, in count_sentences
    tokenizer = _get_sentence_tokenizer()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/azureml/cr/j/95f3ce02c0cc4741bfbb2fb3724411eb/exe/wd/eureka_ml_insights/metrics/ifeval_instruction_utils.py", line 1673, in _get_sentence_tokenizer
    from nltk.tokenize import PunktTokenizer
ImportError: cannot import name 'PunktTokenizer' from 'nltk.tokenize' (/azureml-envs/azureml_5fab4ad31daaaef6f9e1df39f28761b7/lib/python3.11/site-packages/nltk/tokenize/__init__.py)

```

**Comment by lalo** [comment]
This depends on version of nltk so this type of error would point to wrong version.
